version: '3'

services:

  mysql-development:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: helloworld
      MYSQL_DATABASE: mydatabase
      # MYSQL_ADMIN: root
    ports:
      - "3308:3306"
  
  admin:    
    image: adminer    
    ports:      
      - "8081:8080"